// source: Events/AggregateEventCommitResponse.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Events_CommittedAggregateEvents_pb = require('../Events/CommittedAggregateEvents_pb.js');
goog.object.extend(proto, Events_CommittedAggregateEvents_pb);
goog.exportSymbol('proto.dolittle.runtime.events.AggregateEventCommitResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dolittle.runtime.events.AggregateEventCommitResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolittle.runtime.events.AggregateEventCommitResponse.displayName = 'proto.dolittle.runtime.events.AggregateEventCommitResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dolittle.runtime.events.AggregateEventCommitResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolittle.runtime.events.AggregateEventCommitResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    reason: jspb.Message.getFieldWithDefault(msg, 2, ""),
    events: (f = msg.getEvents()) && Events_CommittedAggregateEvents_pb.CommittedAggregateEvents.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolittle.runtime.events.AggregateEventCommitResponse}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolittle.runtime.events.AggregateEventCommitResponse;
  return proto.dolittle.runtime.events.AggregateEventCommitResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolittle.runtime.events.AggregateEventCommitResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolittle.runtime.events.AggregateEventCommitResponse}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    case 3:
      var value = new Events_CommittedAggregateEvents_pb.CommittedAggregateEvents;
      reader.readMessage(value,Events_CommittedAggregateEvents_pb.CommittedAggregateEvents.deserializeBinaryFromReader);
      msg.setEvents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolittle.runtime.events.AggregateEventCommitResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolittle.runtime.events.AggregateEventCommitResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEvents();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      Events_CommittedAggregateEvents_pb.CommittedAggregateEvents.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.dolittle.runtime.events.AggregateEventCommitResponse} returns this
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string reason = 2;
 * @return {string}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dolittle.runtime.events.AggregateEventCommitResponse} returns this
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional CommittedAggregateEvents events = 3;
 * @return {?proto.dolittle.runtime.events.CommittedAggregateEvents}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.getEvents = function() {
  return /** @type{?proto.dolittle.runtime.events.CommittedAggregateEvents} */ (
    jspb.Message.getWrapperField(this, Events_CommittedAggregateEvents_pb.CommittedAggregateEvents, 3));
};


/**
 * @param {?proto.dolittle.runtime.events.CommittedAggregateEvents|undefined} value
 * @return {!proto.dolittle.runtime.events.AggregateEventCommitResponse} returns this
*/
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.setEvents = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dolittle.runtime.events.AggregateEventCommitResponse} returns this
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.clearEvents = function() {
  return this.setEvents(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolittle.runtime.events.AggregateEventCommitResponse.prototype.hasEvents = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.dolittle.runtime.events);
