// source: Events.Processing/EventHandlers.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Artifacts_Artifact_pb = require('../Artifacts/Artifact_pb.js');
goog.object.extend(proto, Artifacts_Artifact_pb);
var Events_CommittedEvent_pb = require('../Events/CommittedEvent_pb.js');
goog.object.extend(proto, Events_CommittedEvent_pb);
goog.exportSymbol('proto.dolittle.runtime.events.processing.EventHandlerArguments', null, global);
goog.exportSymbol('proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse', null, global);
goog.exportSymbol('proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.displayName = 'proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.displayName = 'proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dolittle.runtime.events.processing.EventHandlerArguments.repeatedFields_, null);
};
goog.inherits(proto.dolittle.runtime.events.processing.EventHandlerArguments, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolittle.runtime.events.processing.EventHandlerArguments.displayName = 'proto.dolittle.runtime.events.processing.EventHandlerArguments';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    callnumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    event: (f = msg.getEvent()) && Events_CommittedEvent_pb.CommittedEvent.toObject(includeInstance, f),
    partition: msg.getPartition_asB64(),
    executioncontext: msg.getExecutioncontext_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest;
  return proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCallnumber(value);
      break;
    case 2:
      var value = new Events_CommittedEvent_pb.CommittedEvent;
      reader.readMessage(value,Events_CommittedEvent_pb.CommittedEvent.deserializeBinaryFromReader);
      msg.setEvent(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPartition(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setExecutioncontext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCallnumber();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getEvent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      Events_CommittedEvent_pb.CommittedEvent.serializeBinaryToWriter
    );
  }
  f = message.getPartition_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getExecutioncontext_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * optional uint64 callNumber = 1;
 * @return {number}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getCallnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.setCallnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional dolittle.runtime.events.CommittedEvent event = 2;
 * @return {?proto.dolittle.runtime.events.CommittedEvent}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getEvent = function() {
  return /** @type{?proto.dolittle.runtime.events.CommittedEvent} */ (
    jspb.Message.getWrapperField(this, Events_CommittedEvent_pb.CommittedEvent, 2));
};


/**
 * @param {?proto.dolittle.runtime.events.CommittedEvent|undefined} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} returns this
*/
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.setEvent = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.clearEvent = function() {
  return this.setEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.hasEvent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes partition = 3;
 * @return {!(string|Uint8Array)}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getPartition = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes partition = 3;
 * This is a type-conversion wrapper around `getPartition()`
 * @return {string}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getPartition_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPartition()));
};


/**
 * optional bytes partition = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPartition()`
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getPartition_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPartition()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.setPartition = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes executionContext = 4;
 * @return {!(string|Uint8Array)}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getExecutioncontext = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes executionContext = 4;
 * This is a type-conversion wrapper around `getExecutioncontext()`
 * @return {string}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getExecutioncontext_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getExecutioncontext()));
};


/**
 * optional bytes executionContext = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getExecutioncontext()`
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.getExecutioncontext_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getExecutioncontext()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerRuntimeToClientRequest.prototype.setExecutioncontext = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    callnumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    succeeded: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    retry: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    retrytimeout: jspb.Message.getFieldWithDefault(msg, 4, 0),
    failurereason: jspb.Message.getFieldWithDefault(msg, 5, ""),
    executioncontext: msg.getExecutioncontext_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse;
  return proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCallnumber(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSucceeded(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRetry(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRetrytimeout(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFailurereason(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setExecutioncontext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCallnumber();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getSucceeded();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRetry();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getRetrytimeout();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getFailurereason();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getExecutioncontext_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional uint64 callNumber = 1;
 * @return {number}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getCallnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.setCallnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool succeeded = 2;
 * @return {boolean}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getSucceeded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.setSucceeded = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool retry = 3;
 * @return {boolean}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getRetry = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.setRetry = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional uint32 retryTimeout = 4;
 * @return {number}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getRetrytimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.setRetrytimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string failureReason = 5;
 * @return {string}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getFailurereason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.setFailurereason = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bytes executionContext = 6;
 * @return {!(string|Uint8Array)}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getExecutioncontext = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes executionContext = 6;
 * This is a type-conversion wrapper around `getExecutioncontext()`
 * @return {string}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getExecutioncontext_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getExecutioncontext()));
};


/**
 * optional bytes executionContext = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getExecutioncontext()`
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.getExecutioncontext_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getExecutioncontext()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerClientToRuntimeResponse.prototype.setExecutioncontext = function(value) {
  return jspb.Message.setProto3BytesField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.toObject = function(opt_includeInstance) {
  return proto.dolittle.runtime.events.processing.EventHandlerArguments.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerArguments} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventhandler: msg.getEventhandler_asB64(),
    stream: msg.getStream_asB64(),
    typesList: jspb.Message.toObjectList(msg.getTypesList(),
    Artifacts_Artifact_pb.Artifact.toObject, includeInstance),
    partitioned: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerArguments}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolittle.runtime.events.processing.EventHandlerArguments;
  return proto.dolittle.runtime.events.processing.EventHandlerArguments.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerArguments} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerArguments}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEventhandler(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setStream(value);
      break;
    case 3:
      var value = new Artifacts_Artifact_pb.Artifact;
      reader.readMessage(value,Artifacts_Artifact_pb.Artifact.deserializeBinaryFromReader);
      msg.addTypes(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPartitioned(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolittle.runtime.events.processing.EventHandlerArguments.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolittle.runtime.events.processing.EventHandlerArguments} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventhandler_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getStream_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTypesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      Artifacts_Artifact_pb.Artifact.serializeBinaryToWriter
    );
  }
  f = message.getPartitioned();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional bytes eventHandler = 1;
 * @return {!(string|Uint8Array)}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getEventhandler = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes eventHandler = 1;
 * This is a type-conversion wrapper around `getEventhandler()`
 * @return {string}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getEventhandler_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEventhandler()));
};


/**
 * optional bytes eventHandler = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEventhandler()`
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getEventhandler_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEventhandler()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerArguments} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.setEventhandler = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes stream = 2;
 * @return {!(string|Uint8Array)}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getStream = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes stream = 2;
 * This is a type-conversion wrapper around `getStream()`
 * @return {string}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getStream_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getStream()));
};


/**
 * optional bytes stream = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getStream()`
 * @return {!Uint8Array}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getStream_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getStream()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerArguments} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.setStream = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * repeated dolittle.runtime.artifacts.Artifact types = 3;
 * @return {!Array<!proto.dolittle.runtime.artifacts.Artifact>}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getTypesList = function() {
  return /** @type{!Array<!proto.dolittle.runtime.artifacts.Artifact>} */ (
    jspb.Message.getRepeatedWrapperField(this, Artifacts_Artifact_pb.Artifact, 3));
};


/**
 * @param {!Array<!proto.dolittle.runtime.artifacts.Artifact>} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerArguments} returns this
*/
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.setTypesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.dolittle.runtime.artifacts.Artifact=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dolittle.runtime.artifacts.Artifact}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.addTypes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.dolittle.runtime.artifacts.Artifact, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerArguments} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.clearTypesList = function() {
  return this.setTypesList([]);
};


/**
 * optional bool partitioned = 4;
 * @return {boolean}
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.getPartitioned = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.dolittle.runtime.events.processing.EventHandlerArguments} returns this
 */
proto.dolittle.runtime.events.processing.EventHandlerArguments.prototype.setPartitioned = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


goog.object.extend(exports, proto.dolittle.runtime.events.processing);
